# 🧩 NumPy – Création et manipulation de tableaux (01)

---

## 🎯 Objectifs
- Créer des tableaux avec `np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.full`
- Comprendre les **attributs** d'un tableau : `shape`, `ndim`, `size`, `dtype`
- Comprendre le **dtype** et la coercition de type
- Remodeler un tableau avec `reshape()` (y compris avec `-1`)
- Extraire des données avec le **slicing** et l'**indexation**
- Comprendre la différence **vue vs copie**
- Manipuler la diagonale avec `np.diag` et `np.fill_diagonal`

> ℹ️ **Astuce** : Les corrections sont cachées dans des blocs pliables.  
> Cliquez sur **💡 Correction** pour dérouler la solution.

In [ ]:
import numpy as np
print("NumPy version :", np.__version__)

---
## 📝 Partie 1 – Créer un tableau NumPy

### 🔎 `np.array()` — depuis une liste Python

La façon la plus directe de créer un tableau NumPy est de convertir une liste Python existante.

```python
# Tableau 1D (une seule ligne de valeurs)
a = np.array([10, 20, 30, 40])

# Tableau 2D (un tableau avec lignes et colonnes) — liste de listes
M = np.array([[1, 2, 3],
              [4, 5, 6]])
```

### 🔎 Le `dtype` — quel type de nombre est stocké ?

Tous les éléments d'un tableau NumPy doivent avoir **le même type**. C'est ce qu'on appelle le `dtype` (data type).

Les types les plus courants :

| `dtype` | Ce que c'est | Exemple de valeur |
|---------|-------------|------------------|
| `int64` | Nombre entier | `42`, `-7`, `0` |
| `float64` | Nombre décimal | `3.14`, `-0.5`, `1.0` |
| `bool` | Vrai ou Faux | `True`, `False` |

> 💡 Le chiffre après `int` ou `float` (32, 64…) indique la **précision** — plus le chiffre est grand, plus NumPy peut stocker des valeurs grandes ou précises. En pratique, `int64` et `float64` sont les valeurs par défaut et suffisent pour la quasi-totalité des cas.

NumPy choisit automatiquement le dtype selon ce que vous lui donnez :

```python
np.array([1, 2, 3])       # → dtype int64   (que des entiers)
np.array([1.0, 2, 3])     # → dtype float64 (un flottant → tout devient flottant)
np.array([True, False])   # → dtype bool

# On peut aussi forcer un dtype
np.array([1, 2, 3], dtype=np.float64)  # force float64 même avec des entiers
```

> ⚠️ **Piège classique** : si votre tableau est de type entier et que vous essayez d'y mettre un nombre décimal, NumPy **tronque** la partie décimale sans vous prévenir.
> ```python
> a = np.array([1, 2, 3])   # dtype int64
> a[0] = 1.9                # → stocke 1, pas 1.9 ! (la partie .9 est perdue)
> ```
> Pour éviter ça, créez votre tableau en `float64` : `np.array([1, 2, 3], dtype=float)`

In [ ]:
import numpy as np

# Tableau 1D
ventes = np.array([12, 15, 10, 18, 14])
print("Ventes :", ventes)
print("Type de l'objet :", type(ventes))
print("dtype            :", ventes.dtype)

print()

# Tableau 2D : ventes par saveur (lignes) sur 4 jours (colonnes)
ventes_2d = np.array([[12, 15, 13, 18],   # Margherita
                      [10, 16, 14, 20],   # Reine
                      [ 8, 11,  9, 12]])  # Végétarienne
print("Ventes 2D :\n", ventes_2d)

print()

# Coercition de type
mixte = np.array([1, 2.5, 3])
print("Tableau mixte int/float :", mixte, "| dtype:", mixte.dtype)

# Forcer un dtype
force = np.array([1, 2, 3], dtype=np.float32)
print("dtype forcé float32 :", force, "| dtype:", force.dtype)

👉 **Exercice 1** : Créez les tableaux suivants et affichez leur `dtype` :
1. Un tableau 1D de 5 entiers représentant des températures : `[18, 22, 25, 19, 21]`
2. Un tableau 2D 2×3 représentant des prix HT (flottants) : ligne 1 = `[10.5, 20.0, 8.99]`, ligne 2 = `[15.0, 5.5, 30.0]`
3. Essayez d'affecter `3.9` à `tab1[0]` et observez ce qui se passe.

In [ ]:
import numpy as np

# TODO 1 : tableau 1D de températures entières
tab1 = ...
print("tab1 :", tab1, "| dtype :", tab1.dtype)

# TODO 2 : tableau 2D de prix flottants
tab2 = ...
print("tab2 :\n", tab2, "| dtype :", tab2.dtype)

# TODO 3 : affecter 3.9 à tab1[0] et afficher le résultat
tab1[0] = ...
print("tab1 après affectation de 3.9 :", tab1)  # que se passe-t-il ?

<details>
<summary>💡 Correction</summary>

```python
import numpy as np

tab1 = np.array([18, 22, 25, 19, 21])
print("tab1 :", tab1, "| dtype :", tab1.dtype)   # dtype: int64

tab2 = np.array([[10.5, 20.0, 8.99],
                 [15.0,  5.5, 30.0]])
print("tab2 :\n", tab2, "| dtype :", tab2.dtype)  # dtype: float64

tab1[0] = 3.9
print("tab1 après affectation de 3.9 :", tab1)
# → [3 22 25 19 21]  ← 3.9 est tronqué à 3 car le tableau est int64 !
# C'est le piège de la coercition silencieuse.
```
</details>

---
## 📝 Partie 2 – Fonctions de création rapide

### 🔎 Les fonctions essentielles

| Fonction | Ce qu'elle crée | Exemple |
|----------|----------------|--------|
| `np.zeros(shape)` | Tableau rempli de **0** — utile pour initialiser avant de remplir | `np.zeros((3, 4))` |
| `np.ones(shape)` | Tableau rempli de **1** — utile comme point de départ pour des calculs | `np.ones((2, 3))` |
| `np.full(shape, val)` | Tableau rempli d'une **valeur de votre choix** | `np.full((2, 2), 7)` |
| `np.eye(n)` | Matrice carrée avec des **1 sur la diagonale**, 0 ailleurs | `np.eye(3)` |
| `np.arange(start, stop, step)` | Suite de nombres avec un **pas fixe** | `np.arange(0, 10, 2)` |
| `np.linspace(start, stop, N)` | **N valeurs** régulièrement espacées entre start et stop | `np.linspace(0, 1, 5)` |
| `np.random.randint(low, high, shape)` | Entiers **aléatoires** | `np.random.randint(1, 10, (3, 4))` |

**`np.eye(n)` — la matrice identité :** c'est une matrice carrée particulière où la diagonale vaut 1 et tout le reste vaut 0. Elle est utilisée en algèbre linéaire (elle joue le rôle du "1" pour la multiplication de matrices). Vous la rencontrerez souvent dans les algorithmes de ML.

```python
np.eye(3)
# → [[1. 0. 0.]
#    [0. 1. 0.]
#    [0. 0. 1.]]
```

### 🔎 `arange` vs `linspace` : quelle différence ?

Les deux créent une suite de nombres, mais avec une logique différente :

```python
# arange : vous fixez le PAS entre chaque valeur
#          (le stop est EXCLU, comme range() en Python)
np.arange(0, 1, 0.25)    # → [0.   0.25  0.5   0.75]   (s'arrête avant 1)

# linspace : vous fixez le NOMBRE DE POINTS voulu
#            (le stop est INCLUS)
np.linspace(0, 1, 5)     # → [0.   0.25  0.5   0.75  1.]  (5 points, 1 inclus)
```

> 💡 Utilisez `arange` quand vous savez quel pas vous voulez.  
> Utilisez `linspace` quand vous savez combien de points vous voulez (très utile pour tracer des courbes).

In [ ]:
import numpy as np

# np.zeros et np.ones : initialisations courantes
zeros = np.zeros((2, 3))
print("np.zeros((2,3)) :\n", zeros)
print("dtype :", zeros.dtype)   # float64 par défaut

uns = np.ones((2, 3), dtype=int)  # on peut forcer int
print("\nnp.ones((2,3), dtype=int) :\n", uns)

# np.full : initialisation à une valeur fixe
grille = np.full((3, 4), fill_value=-1)
print("\nnp.full((3,4), -1) :\n", grille)

# np.eye : matrice identité (1 sur la diagonale, 0 ailleurs)
identite = np.eye(4, dtype=int)
print("\nnp.eye(4) :\n", identite)

# np.arange
print("\nnp.arange(0, 10, 2) :", np.arange(0, 10, 2))
print("np.arange(5.0)      :", np.arange(5.0))

# np.linspace
print("\nnp.linspace(0, 1, 5) :", np.linspace(0, 1, 5))
print("np.linspace(0, 100, 6) :", np.linspace(0, 100, 6))

👉 **Exercice 2** : Créez les tableaux suivants :
1. Une matrice 4×5 remplie de zéros entiers (`dtype=int`)
2. Une matrice identité 3×3
3. 7 températures régulièrement espacées entre 0°C et 100°C (inclus) avec `linspace`
4. Les multiples de 3 de 0 à 30 inclus avec `arange`

In [ ]:
import numpy as np

# TODO 1 : matrice 4×5 de zéros entiers
m1 = ...
print("Matrice zéros 4×5 :\n", m1)

# TODO 2 : matrice identité 3×3
m2 = ...
print("\nIdentité 3×3 :\n", m2)

# TODO 3 : 7 températures de 0 à 100 (linspace)
temps = ...
print("\n7 températures :", temps)

# TODO 4 : multiples de 3 de 0 à 30 inclus
mult3 = ...
print("Multiples de 3 :", mult3)

<details>
<summary>💡 Correction</summary>

```python
import numpy as np

# 1 — zeros entiers
m1 = np.zeros((4, 5), dtype=int)
print("Matrice zéros 4×5 :\n", m1)

# 2 — identité
m2 = np.eye(3, dtype=int)
print("\nIdentité 3×3 :\n", m2)

# 3 — linspace : 7 points de 0 à 100 inclus
temps = np.linspace(0, 100, 7)
print("\n7 températures :", temps)
# → [  0.          16.66...  33.33...  50.  66.66...  83.33...  100.]

# 4 — arange : 0, 3, 6, ..., 30  (stop = 31 car stop est exclu)
mult3 = np.arange(0, 31, 3)
print("Multiples de 3 :", mult3)
```
</details>

---
## 📝 Partie 3 – Attributs d'un tableau

### 🔎 Les 4 attributs essentiels

Tout tableau NumPy possède des **attributs** (pas des méthodes — pas de parenthèses) qui décrivent sa structure :

| Attribut | Description | Exemple |
|----------|-------------|--------|
| `.shape` | Dimensions sous forme de tuple | `(3, 4)` = 3 lignes, 4 colonnes |
| `.ndim` | Nombre de dimensions | `2` pour une matrice |
| `.size` | Nombre total d'éléments | `12` pour une matrice 3×4 |
| `.dtype` | Type des données | `int64`, `float64`… |

```
Tableau A de shape (3, 4) :
        col0  col1  col2  col3
ligne0 [  0     1     2     3  ]
ligne1 [  4     5     6     7  ]
ligne2 [  8     9    10    11  ]

A.shape → (3, 4)    # 3 lignes, 4 colonnes
A.ndim  → 2         # 2 dimensions
A.size  → 12        # 3 × 4 = 12 éléments
A.dtype → int64
```

In [ ]:
import numpy as np

# Ventes de 3 saveurs de pizza sur 4 jours
A = np.array([[12, 15, 13, 18],
              [10, 16, 14, 20],
              [ 8, 11,  9, 12]])

print("Tableau A :\n", A)
print()
print("shape :", A.shape)   # (3, 4) — 3 saveurs × 4 jours
print("ndim  :", A.ndim)    # 2 dimensions
print("size  :", A.size)    # 12 valeurs au total
print("dtype :", A.dtype)   # int64

print()
# Accéder à shape[0] (nb lignes) et shape[1] (nb colonnes)
nb_saveurs, nb_jours = A.shape
print(f"{nb_saveurs} saveurs × {nb_jours} jours = {A.size} ventes au total")

👉 **Exercice 3** : Créez un tableau aléatoire et explorez ses attributs.
1. Créez un tableau de 24 entiers aléatoires entre 1 et 100 avec `np.random.randint(1, 101, 24)`
2. Affichez ses 4 attributs (`shape`, `ndim`, `size`, `dtype`)
3. Affichez le nombre de lignes et de colonnes séparément en utilisant `.shape[0]` et `.shape[1]` — mais attendez, ça marche ? Pourquoi ?
4. Affichez la taille en octets du tableau (`.nbytes`)

In [ ]:
import numpy as np
np.random.seed(42)  # pour avoir les mêmes résultats que la correction

# TODO 1 : tableau de 24 entiers aléatoires entre 1 et 100
T = ...

# TODO 2 : afficher les 4 attributs
print("shape :", ...)
print("ndim  :", ...)
print("size  :", ...)
print("dtype :", ...)

# TODO 3 : essayer d'accéder à shape[1] — que se passe-t-il ?
print("shape[0] :", ...)
# print("shape[1] :", ...)   # décommenter et observer

# TODO 4 : taille en octets
print("nbytes :", ...)

<details>
<summary>💡 Correction</summary>

```python
import numpy as np
np.random.seed(42)

T = np.random.randint(1, 101, 24)

print("shape :", T.shape)   # (24,)  — tuple à 1 élément : c'est un vecteur 1D
print("ndim  :", T.ndim)    # 1
print("size  :", T.size)    # 24
print("dtype :", T.dtype)   # int64

print("shape[0] :", T.shape[0])   # 24 — la longueur du vecteur
# print("shape[1] :", T.shape[1]) # ← IndexError ! Un vecteur 1D n'a pas de dimension 1
# Il faudrait reshape(4, 6) par exemple pour avoir 2 dimensions.

print("nbytes :", T.nbytes)   # 24 × 8 = 192 octets (int64 = 8 octets/élément)
```
</details>

---
## 📝 Partie 4 – Remodeler un tableau : `reshape()`

### 🔎 Comment ça marche ?

`reshape()` change la **forme** d'un tableau sans modifier ses données ni les copier. Les données sont simplement réorganisées dans une nouvelle structure.

**Contrainte** : le nombre total d'éléments doit rester identique.
```
arange(12)  →  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]  (size=12)
reshape(3,4) →  [[ 0  1  2  3]      shape=(3,4), size=12 ✅
                 [ 4  5  6  7]
                 [ 8  9 10 11]]
reshape(2,5) →  ValueError !         2×5=10 ≠ 12 ❌
```

### 🔎 Le `-1` dans reshape : calcul automatique

`-1` signifie : *"calcule cette dimension automatiquement"*. Très utile quand on ne connaît pas à l'avance le nombre de lignes ou de colonnes.

```python
A = np.arange(12)

A.reshape(3, 4)    # explicite : 3 lignes, 4 colonnes
A.reshape(-1, 4)   # automatique : ? lignes, 4 colonnes → 12/4 = 3 lignes
A.reshape(3, -1)   # automatique : 3 lignes, ? colonnes → 12/3 = 4 colonnes
A.reshape(-1)      # aplatir en 1D (équivalent à .flatten())
```

### 🔎 Transposition

`.T` **transpose** un tableau : les lignes deviennent des colonnes et inversement.

```python
A.shape     # (3, 4)
A.T.shape   # (4, 3)
```

In [ ]:
import numpy as np

# 12 ventes journalières → organisées par semaine (3 semaines × 4 jours)
ventes = np.arange(12)
print("Ventes brutes   :", ventes)
print("Shape           :", ventes.shape)

par_semaine = ventes.reshape(3, 4)
print("\nPar semaine (3×4) :\n", par_semaine)

# Le -1 : NumPy calcule tout seul
auto = ventes.reshape(-1, 4)   # "je veux 4 colonnes, calcule les lignes"
print("\nreshape(-1, 4) :\n", auto)

auto2 = ventes.reshape(3, -1)  # "je veux 3 lignes, calcule les colonnes"
print("reshape(3, -1) :\n", auto2)

# Transposition
print("\nShape avant .T :", par_semaine.shape)
print("Shape après .T :", par_semaine.T.shape)
print("Tableau transposé :\n", par_semaine.T)

👉 **Exercice 4** : Réorganisation de données.

Vous avez 24 mesures de température prises toutes les heures pendant une journée (sur 3 capteurs).
1. Créez un tableau `mesures = np.arange(1, 25)` (24 valeurs de 1 à 24).
2. Remodelé en 8 lignes et 3 colonnes (8 blocs de 3 capteurs) avec `reshape`.
3. Remodelé en 3 lignes et 8 colonnes (3 capteurs × 8 relevés) avec `-1`.
4. Affichez la transposée du résultat de l'étape 3 et vérifiez que sa shape correspond à l'étape 2.

In [ ]:
import numpy as np

# TODO 1 : créer le tableau de 24 mesures
mesures = ...
print("Mesures brutes :", mesures)

# TODO 2 : reshape 8×3
blocs = mesures.reshape(...)
print("\n8 blocs × 3 capteurs :\n", blocs)

# TODO 3 : 3 capteurs × 8 relevés avec -1
capteurs = mesures.reshape(...)
print("\n3 capteurs × 8 relevés :\n", capteurs)

# TODO 4 : transposée
print("\nTransposée :\n", capteurs...)
print("Shape transposée :", capteurs.T.shape)  # doit être (8, 3)

<details>
<summary>💡 Correction</summary>

```python
import numpy as np

mesures = np.arange(1, 25)
print("Mesures brutes :", mesures)

blocs = mesures.reshape(8, 3)
print("\n8 blocs × 3 capteurs :\n", blocs)

capteurs = mesures.reshape(3, -1)   # -1 → 24/3 = 8 colonnes
print("\n3 capteurs × 8 relevés :\n", capteurs)

print("\nTransposée :\n", capteurs.T)
print("Shape transposée :", capteurs.T.shape)   # (8, 3) = même que blocs ✅
```
</details>

---
## 📝 Partie 5 – Slicing et indexation

### 🔎 Comment découper un tableau ?

Le **slicing** permet d'extraire une partie continue d'un tableau. La syntaxe est la même que pour les listes Python, mais en 2D on précise les deux dimensions.

```
A[ligne_debut:ligne_fin, col_debut:col_fin]
        ↑ inclus             ↑ exclu
```

Raccourcis courants :
```python
A[0, :]      # toute la ligne 0   (le : seul = "tout")
A[:, 2]      # toute la colonne 2
A[-1, :]     # dernière ligne     (index négatif)
A[:, -1]     # dernière colonne
A[1:3, 1:3]  # sous-matrice : lignes 1 et 2, colonnes 1 et 2
A[::-1, :]   # toutes les lignes dans l'ordre inverse
A[:, ::2]    # une colonne sur deux (colonnes 0, 2, 4…)
```

### 🔎 Vue vs Copie — le piège le plus fréquent avec NumPy

Quand vous découpez un tableau avec le slicing, vous obtenez une **vue** — pas une copie indépendante. C'est une **fenêtre sur le même tableau en mémoire**.

**Analogie :** imaginez un grand tableau blanc dans une salle. Vous pouvez pointer une zone avec votre doigt (c'est une vue) ou prendre une photo de cette zone (c'est une copie). Si quelqu'un modifie le tableau blanc dans la zone que vous pointez, votre "vue" change aussi. Mais votre photo, elle, reste inchangée.

```python
A = np.arange(9).reshape(3, 3)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

# Vue : B pointe sur le coin supérieur gauche de A
B = A[0:2, 0:2]   # → [[0 1]
                  #     [3 4]]

B[0, 0] = 999     # on modifie B...
print(A[0, 0])    # → 999  !!! A a aussi changé !

# Copie : C est indépendant de A
C = A[0:2, 0:2].copy()   # on prend une "photo"
C[0, 0] = 777
print(A[0, 0])    # → 999  (A n'a pas changé)
```

| Opération | Résultat | Modifier le résultat… |
|-----------|----------|----------------------|
| Slicing `A[0:2, 0:2]` | **Vue** — fenêtre sur A | …modifie aussi A |
| `.copy()` | **Copie** — tableau indépendant | …ne modifie pas A |

> ⚠️ **Règle simple :** dès que vous voulez travailler sur un extrait sans risquer de modifier le tableau original, appelez **toujours `.copy()`**.

In [ ]:
import numpy as np

# Matrice météo : 5 jours × 5 villes
A = np.arange(25).reshape(5, 5)
print("Matrice A :\n", A)
print()

# Ligne 0 (premier jour)
print("Ligne 0 (1er jour)  :", A[0, :])

# Colonne 2 (3e ville)
print("Colonne 2 (3e ville):", A[:, 2])

# Dernière ligne
print("Dernière ligne      :", A[-1, :])

# Sous-matrice centrale 3×3
print("Sous-matrice [1:4, 1:4] :\n", A[1:4, 1:4])

# Ordre inverse des lignes
print("Lignes inversées :\n", A[::-1, :])

# Colonnes paires seulement
print("Colonnes paires (::2):", A[0, ::2])

In [ ]:
import numpy as np

A = np.arange(25).reshape(5, 5)
print("A original :\n", A)

# --- VUE : slicing ---
B = A[0:2, 0:2]   # B est une VUE sur A
print("\nB (vue sur A[0:2, 0:2]) :\n", B)

B[0, 0] = 999      # modifier B modifie AUSSI A !
print("\nAprès B[0,0] = 999 :")
print("B :\n", B)
print("A (modifié !) :\n", A)

# --- COPIE : .copy() ---
A2 = np.arange(25).reshape(5, 5)  # on repart d'un A propre
C = A2[0:2, 0:2].copy()           # C est une COPIE indépendante
C[0, 0] = 888
print("\nAprès C[0,0] = 888 :")
print("C :\n", C)
print("A2 (inchangé) :\n", A2)

👉 **Exercice 5** : Travaillez sur le tableau de ventes de pizzas suivant.

```
Ventes : 3 saveurs × 5 jours
         Lun  Mar  Mer  Jeu  Ven
Margherita [ 12   15   13   18   20 ]
Reine      [ 10   16   14   20   22 ]
Végé       [  8   11    9   12   15 ]
```

1. Extrayez la **colonne Mercredi** (index 2)
2. Extrayez les ventes du **week-end** — ici Jeudi et Vendredi (colonnes 3 et 4)
3. Extrayez les ventes des **2 premières saveurs** sur les **3 premiers jours**
4. Ajoutez `+5` à toute la **dernière ligne** (Végé) via slicing (sans boucle)
5. Vérifiez que le tableau original a bien été modifié (effet vue)

In [ ]:
import numpy as np

ventes = np.array([[12, 15, 13, 18, 20],
                   [10, 16, 14, 20, 22],
                   [ 8, 11,  9, 12, 15]])
print("Tableau original :\n", ventes)

# TODO 1 : colonne Mercredi (index 2)
mercredi = ...
print("\nMercredi :", mercredi)

# TODO 2 : colonnes Jeudi + Vendredi
weekend = ...
print("Week-end :\n", weekend)

# TODO 3 : 2 premières saveurs × 3 premiers jours
debut = ...
print("Début de semaine (2 saveurs × 3 jours) :\n", debut)

# TODO 4 : ajouter +5 à la dernière ligne via slicing
ventes[...] += 5

# TODO 5 : vérifier la modification
print("\nTableau après +5 sur Végé :\n", ventes)

<details>
<summary>💡 Correction</summary>

```python
import numpy as np

ventes = np.array([[12, 15, 13, 18, 20],
                   [10, 16, 14, 20, 22],
                   [ 8, 11,  9, 12, 15]])
print("Tableau original :\n", ventes)

# 1 — colonne Mercredi
mercredi = ventes[:, 2]
print("\nMercredi :", mercredi)   # [13 14  9]

# 2 — colonnes Jeudi + Vendredi
weekend = ventes[:, 3:5]
print("Week-end :\n", weekend)

# 3 — 2 premières lignes × 3 premières colonnes
debut = ventes[0:2, 0:3]
print("Début de semaine :\n", debut)

# 4 — +5 sur la dernière ligne (slicing = vue → modifie ventes)
ventes[-1, :] += 5

# 5 — le tableau original est bien modifié
print("\nTableau après +5 sur Végé :\n", ventes)
# Ligne Végé : [13 16 14 17 20]  ✅
```
</details>

---
## 📝 Partie 6 – Diagonale : `np.diag` et `np.fill_diagonal`

### 🔎 Deux usages de `np.diag`

`np.diag` a un **comportement différent** selon ce qu'on lui passe :

```python
# Cas 1 : passer une matrice → extraire la diagonale (retourne un vecteur)
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.diag(M)    # → [1, 5, 9]

# Cas 2 : passer un vecteur → construire une matrice diagonale
v = np.array([10, 20, 30])
np.diag(v)    # → [[10,  0,  0],
              #     [ 0, 20,  0],
              #     [ 0,  0, 30]]
```

`np.fill_diagonal(M, val)` modifie la diagonale **en place** (sur le tableau original).

```python
np.fill_diagonal(M, 0)   # met tous les éléments diagonaux à 0
```

In [ ]:
import numpy as np

M = np.arange(16).reshape(4, 4)
print("Matrice M :\n", M)

# Extraire la diagonale
print("\nDiagonale extraite :", np.diag(M))

# Construire une matrice diagonale depuis un vecteur
v = np.array([10, 20, 30, 40])
D = np.diag(v)
print("\nMatrice diagonale depuis v :\n", D)

# Modifier la diagonale en place
np.fill_diagonal(M, 99)
print("\nM après fill_diagonal(M, 99) :\n", M)

👉 **Exercice 6** : Construisez la matrice suivante **uniquement** avec `np.zeros`, du slicing et `np.fill_diagonal` :

```
[[1 2 2 2]
 [2 1 0 2]
 [2 0 1 2]
 [2 2 2 1]]
```

Indice : commencez par remplir les bords à 2, puis la diagonale à 1.

In [ ]:
import numpy as np

# TODO : construire la matrice 4×4 ci-dessus
M = np.zeros((4, 4), dtype=int)

# Remplir les bords (ligne 0, ligne -1, col 0, col -1) avec 2
M[0, :]  = ...
M[-1, :] = ...
M[:, 0]  = ...
M[:, -1] = ...

# Mettre la diagonale à 1
np.fill_diagonal(...)

print(M)

<details>
<summary>💡 Correction</summary>

```python
import numpy as np

M = np.zeros((4, 4), dtype=int)

# Bords à 2 (on peut tout faire en une ligne grâce aux assignations chaînées)
M[0, :] = M[-1, :] = M[:, 0] = M[:, -1] = 2

# Diagonale à 1 (écrase les coins qui étaient à 2)
np.fill_diagonal(M, 1)

print(M)
# [[1 2 2 2]
#  [2 1 0 2]
#  [2 0 1 2]
#  [2 2 2 1]]
```
</details>

---
## ✅ Récapitulatif

| Concept | Ce qu'il faut retenir |
|---------|----------------------|
| `np.array()` | Convertit une liste en tableau NumPy |
| `dtype` | Type fixe de tous les éléments — attention à la coercition silencieuse |
| `np.zeros/ones/full` | Initialisations rapides — ne pas oublier le tuple pour la shape |
| `np.arange` | Suite arithmétique avec un pas — stop exclu |
| `np.linspace` | N points entre start et stop — stop inclus |
| `.shape/.ndim/.size` | Attributs (sans parenthèses) qui décrivent la structure |
| `reshape(m, n)` | Remodeler — le produit m×n doit être égal à `.size` |
| `reshape(-1, n)` | NumPy calcule automatiquement la dimension manquante |
| `.T` | Transposition — les lignes deviennent des colonnes |
| Slicing `A[r1:r2, c1:c2]` | Vue — modifier le résultat modifie A |
| `.copy()` | Copie indépendante — modifier ne touche pas A |
| `np.diag(M)` | Extrait la diagonale d'une matrice |
| `np.diag(v)` | Construit une matrice diagonale depuis un vecteur |
| `np.fill_diagonal(M, val)` | Modifie la diagonale en place |

---
📘 **Prochain notebook → `02` : Opérations vectorisées et broadcasting**